name: Django Package CI with uv + tox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        django-version: ["4.2", "5.0"]
      fail-fast: false
    name: Python ${{ matrix.python-version }} / Django ${{ matrix.django-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Run tox
        env:
          DJANGO: ${{ matrix.django-version }}
        run: tox